# fly.toml app configuration file generated for btpgo-api on 2025-10-30T10:45:35+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'btpgo-api'
primary_region = 'cdg'

[build]
  dockerfile = "backend/Dockerfile"

[env]
  PORT = "4000"

[deploy]
  release_command = "sh -lc 'npx prisma migrate deploy'"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    port = 4000
    type = "http"
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
